In [1]:
import torch
import torch.nn as nn
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix,classification_report
import warnings

data = datasets.load_breast_cancer()
X,y = data.data,data.target

n_samples, n_features = X.shape
X_train, X_test, y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=123)

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

X_train = torch.from_numpy(X_train.astype(np.float32))
X_test = torch.from_numpy(X_test.astype(np.float32))
y_train = torch.from_numpy(y_train.astype(np.float32))
y_test = torch.from_numpy(y_test.astype(np.float32))

y_train = y_train.view(y_train.shape[0],1)
y_test = y_test.view(y_test.shape[0], 1)

In [2]:


from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder
from xgboost import XGBClassifier
from catboost import CatBoostClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
import pandas as pd

In [3]:
classifiers = [['Multi-layer Neural Network :', MLPClassifier(max_iter=1000)],
               ['LogisticRegression :', LogisticRegression(max_iter=1000)],
               ['ExtraTreesClassifier :', ExtraTreesClassifier()],
               ['DecisionTree :',DecisionTreeClassifier()],
               ['RandomForest :',RandomForestClassifier()], 
               ['Naive Bayes :', GaussianNB()],
               ['KNeighbours :', KNeighborsClassifier()],
               ['SVM :', SVC()],
               ['AdaBoostClassifier :', AdaBoostClassifier()],
               ['GradientBoostingClassifier: ', GradientBoostingClassifier()],
               ['XGB :', XGBClassifier()]
               ]

predictions_df = pd.DataFrame()
predictions_df['action'] = y_test

for name,classifier in classifiers:
    classifier = classifier
    classifier.fit(X_train, y_train.ravel())
    predictions = classifier.predict(X_test)
    predictions_df[name.strip(" :")] = predictions
    print(name, accuracy_score(y_test, predictions))

ValueError: Cannot set a frame with no defined index and a value that cannot be converted to a Series

In [13]:
from sklearn.ensemble import VotingClassifier
clf1 = MLPClassifier(max_iter=1000)
clf2 = KNeighborsClassifier(n_neighbors=15)
clf3 = XGBClassifier()
clf4 = SVC()
clf5 = RandomForestClassifier()
clf6 = LogisticRegression()
clf7 = GaussianNB()
eclf1 = VotingClassifier(estimators=[('MLP', clf1),('KNN',clf2),('SVM', clf4),('RF',clf5)], voting='hard')
eclf2 = VotingClassifier(estimators=[('MLP', clf1),('RF',clf5),('LogReg',clf6)], voting='soft')
eclf3 = VotingClassifier(estimators=[('MLP', clf1),('LogReg',clf6), ('XGB',clf3)], voting='soft')
estimators = [eclf1,eclf2,eclf3]

for estimator in estimators:
    estimator.fit(X_train,y_train)
    predictions = estimator.predict(X_test)
    print(classification_report(y_test, predictions, digits=3))
    print(confusion_matrix(y_test,predictions))

c:\Users\Antonio\anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:98: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\Antonio\anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:133: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


              precision    recall  f1-score   support

         0.0      0.985     0.985     0.985        68
         1.0      0.990     0.990     0.990       103

    accuracy                          0.988       171
   macro avg      0.988     0.988     0.988       171
weighted avg      0.988     0.988     0.988       171

[[ 67   1]
 [  1 102]]


c:\Users\Antonio\anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:98: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\Antonio\anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:133: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


              precision    recall  f1-score   support

         0.0      0.985     0.971     0.978        68
         1.0      0.981     0.990     0.986       103

    accuracy                          0.982       171
   macro avg      0.983     0.980     0.982       171
weighted avg      0.982     0.982     0.982       171

[[ 66   2]
 [  1 102]]


c:\Users\Antonio\anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:98: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\Antonio\anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:133: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


              precision    recall  f1-score   support

         0.0      0.971     0.985     0.978        68
         1.0      0.990     0.981     0.985       103

    accuracy                          0.982       171
   macro avg      0.981     0.983     0.982       171
weighted avg      0.983     0.982     0.982       171

[[ 67   1]
 [  2 101]]
